//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controller/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""385f77b1-ddf7-4fe2-a4bc-5437047bf5ad"",
            ""actions"": [
                {
                    ""name"": ""HatUp"",
                    ""type"": ""Button"",
                    ""id"": ""afd82317-92be-4d46-b32d-e6a108812e1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HatDown"",
                    ""type"": ""Button"",
                    ""id"": ""4950ebac-559a-4df7-86c0-857a88f07d16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HatLeft"",
                    ""type"": ""Button"",
                    ""id"": ""64878923-f10f-40ab-855c-88ca4f3f89f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HatRight"",
                    ""type"": ""Button"",
                    ""id"": ""4f378d0c-e3c3-411d-bd4d-9af04fd47103"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button3"",
                    ""type"": ""Button"",
                    ""id"": ""403fc5d1-e6ac-4d3f-85e1-2e36673188cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button4"",
                    ""type"": ""Button"",
                    ""id"": ""d6319133-fa47-42f5-afb5-7f07fea9c783"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button2"",
                    ""type"": ""Button"",
                    ""id"": ""ffcd9804-d376-4a25-9bea-57c9bae5c837"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button11"",
                    ""type"": ""Button"",
                    ""id"": ""801e020f-77af-4533-a51d-66437217bb60"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button9"",
                    ""type"": ""Button"",
                    ""id"": ""3c2006b3-bd0b-454e-8312-cc4f79fd445e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button5"",
                    ""type"": ""Button"",
                    ""id"": ""d26b8e35-fe2b-4f30-a323-e5e851323f8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button6"",
                    ""type"": ""Button"",
                    ""id"": ""377a7ba6-fa5f-48d9-bebf-e7540a3d5900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button15"",
                    ""type"": ""Button"",
                    ""id"": ""d1fc1673-79bb-492f-b75f-6fdd0faa05bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button16"",
                    ""type"": ""Button"",
                    ""id"": ""55f99469-0ce2-4c19-b4ed-b43893e5ff22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""289c71af-c8aa-4bd5-95ad-35c229c52149"",
                    ""path"": ""<HID::Joy-Con (L)>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HatUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd1b73f9-6e3f-46c4-8732-07ee4bc7eaaf"",
                    ""path"": ""<HID::Joy-Con (L)>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HatDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6422b81e-d562-4064-8490-feabf46f5c4d"",
                    ""path"": ""<HID::Joy-Con (L)>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HatLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""584a373e-63bc-45f0-935b-2bb7c31137e8"",
                    ""path"": ""<HID::Joy-Con (L)>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HatRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a422c96-4ae8-44e1-b954-ccb8882816ee"",
                    ""path"": ""<HID::Joy-Con (L)>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e30b425a-c715-4162-8be7-47d8b540499f"",
                    ""path"": ""<HID::Joy-Con (L)>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cdd2e7b-12e5-4819-89a0-70067a17ae84"",
                    ""path"": ""<HID::Joy-Con (L)>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7b21233-4a65-48fb-b7b4-e583fa71d256"",
                    ""path"": ""<HID::Joy-Con (L)>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button11"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e6429d-9455-46d2-8ff8-76a626f391ca"",
                    ""path"": ""<HID::Joy-Con (L)>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04b76b59-2830-410a-943e-c435aee091f9"",
                    ""path"": ""<HID::Joy-Con (L)>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""733c829f-2dd7-46b3-bc33-27fb6f11597d"",
                    ""path"": ""<HID::Joy-Con (L)>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d31e4ad-2784-428a-8018-35cf46976026"",
                    ""path"": ""<HID::Joy-Con (L)>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button15"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd926ca5-e0e3-4a6c-8ae2-a93e73cf1e2a"",
                    ""path"": ""<HID::Joy-Con (L)>/button16"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button16"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_HatUp = m_Gameplay.FindAction("HatUp", throwIfNotFound: true);
        m_Gameplay_HatDown = m_Gameplay.FindAction("HatDown", throwIfNotFound: true);
        m_Gameplay_HatLeft = m_Gameplay.FindAction("HatLeft", throwIfNotFound: true);
        m_Gameplay_HatRight = m_Gameplay.FindAction("HatRight", throwIfNotFound: true);
        m_Gameplay_Button3 = m_Gameplay.FindAction("Button3", throwIfNotFound: true);
        m_Gameplay_Button4 = m_Gameplay.FindAction("Button4", throwIfNotFound: true);
        m_Gameplay_Button2 = m_Gameplay.FindAction("Button2", throwIfNotFound: true);
        m_Gameplay_Button11 = m_Gameplay.FindAction("Button11", throwIfNotFound: true);
        m_Gameplay_Button9 = m_Gameplay.FindAction("Button9", throwIfNotFound: true);
        m_Gameplay_Button5 = m_Gameplay.FindAction("Button5", throwIfNotFound: true);
        m_Gameplay_Button6 = m_Gameplay.FindAction("Button6", throwIfNotFound: true);
        m_Gameplay_Button15 = m_Gameplay.FindAction("Button15", throwIfNotFound: true);
        m_Gameplay_Button16 = m_Gameplay.FindAction("Button16", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_HatUp;
    private readonly InputAction m_Gameplay_HatDown;
    private readonly InputAction m_Gameplay_HatLeft;
    private readonly InputAction m_Gameplay_HatRight;
    private readonly InputAction m_Gameplay_Button3;
    private readonly InputAction m_Gameplay_Button4;
    private readonly InputAction m_Gameplay_Button2;
    private readonly InputAction m_Gameplay_Button11;
    private readonly InputAction m_Gameplay_Button9;
    private readonly InputAction m_Gameplay_Button5;
    private readonly InputAction m_Gameplay_Button6;
    private readonly InputAction m_Gameplay_Button15;
    private readonly InputAction m_Gameplay_Button16;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @HatUp => m_Wrapper.m_Gameplay_HatUp;
        public InputAction @HatDown => m_Wrapper.m_Gameplay_HatDown;
        public InputAction @HatLeft => m_Wrapper.m_Gameplay_HatLeft;
        public InputAction @HatRight => m_Wrapper.m_Gameplay_HatRight;
        public InputAction @Button3 => m_Wrapper.m_Gameplay_Button3;
        public InputAction @Button4 => m_Wrapper.m_Gameplay_Button4;
        public InputAction @Button2 => m_Wrapper.m_Gameplay_Button2;
        public InputAction @Button11 => m_Wrapper.m_Gameplay_Button11;
        public InputAction @Button9 => m_Wrapper.m_Gameplay_Button9;
        public InputAction @Button5 => m_Wrapper.m_Gameplay_Button5;
        public InputAction @Button6 => m_Wrapper.m_Gameplay_Button6;
        public InputAction @Button15 => m_Wrapper.m_Gameplay_Button15;
        public InputAction @Button16 => m_Wrapper.m_Gameplay_Button16;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @HatUp.started += instance.OnHatUp;
            @HatUp.performed += instance.OnHatUp;
            @HatUp.canceled += instance.OnHatUp;
            @HatDown.started += instance.OnHatDown;
            @HatDown.performed += instance.OnHatDown;
            @HatDown.canceled += instance.OnHatDown;
            @HatLeft.started += instance.OnHatLeft;
            @HatLeft.performed += instance.OnHatLeft;
            @HatLeft.canceled += instance.OnHatLeft;
            @HatRight.started += instance.OnHatRight;
            @HatRight.performed += instance.OnHatRight;
            @HatRight.canceled += instance.OnHatRight;
            @Button3.started += instance.OnButton3;
            @Button3.performed += instance.OnButton3;
            @Button3.canceled += instance.OnButton3;
            @Button4.started += instance.OnButton4;
            @Button4.performed += instance.OnButton4;
            @Button4.canceled += instance.OnButton4;
            @Button2.started += instance.OnButton2;
            @Button2.performed += instance.OnButton2;
            @Button2.canceled += instance.OnButton2;
            @Button11.started += instance.OnButton11;
            @Button11.performed += instance.OnButton11;
            @Button11.canceled += instance.OnButton11;
            @Button9.started += instance.OnButton9;
            @Button9.performed += instance.OnButton9;
            @Button9.canceled += instance.OnButton9;
            @Button5.started += instance.OnButton5;
            @Button5.performed += instance.OnButton5;
            @Button5.canceled += instance.OnButton5;
            @Button6.started += instance.OnButton6;
            @Button6.performed += instance.OnButton6;
            @Button6.canceled += instance.OnButton6;
            @Button15.started += instance.OnButton15;
            @Button15.performed += instance.OnButton15;
            @Button15.canceled += instance.OnButton15;
            @Button16.started += instance.OnButton16;
            @Button16.performed += instance.OnButton16;
            @Button16.canceled += instance.OnButton16;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @HatUp.started -= instance.OnHatUp;
            @HatUp.performed -= instance.OnHatUp;
            @HatUp.canceled -= instance.OnHatUp;
            @HatDown.started -= instance.OnHatDown;
            @HatDown.performed -= instance.OnHatDown;
            @HatDown.canceled -= instance.OnHatDown;
            @HatLeft.started -= instance.OnHatLeft;
            @HatLeft.performed -= instance.OnHatLeft;
            @HatLeft.canceled -= instance.OnHatLeft;
            @HatRight.started -= instance.OnHatRight;
            @HatRight.performed -= instance.OnHatRight;
            @HatRight.canceled -= instance.OnHatRight;
            @Button3.started -= instance.OnButton3;
            @Button3.performed -= instance.OnButton3;
            @Button3.canceled -= instance.OnButton3;
            @Button4.started -= instance.OnButton4;
            @Button4.performed -= instance.OnButton4;
            @Button4.canceled -= instance.OnButton4;
            @Button2.started -= instance.OnButton2;
            @Button2.performed -= instance.OnButton2;
            @Button2.canceled -= instance.OnButton2;
            @Button11.started -= instance.OnButton11;
            @Button11.performed -= instance.OnButton11;
            @Button11.canceled -= instance.OnButton11;
            @Button9.started -= instance.OnButton9;
            @Button9.performed -= instance.OnButton9;
            @Button9.canceled -= instance.OnButton9;
            @Button5.started -= instance.OnButton5;
            @Button5.performed -= instance.OnButton5;
            @Button5.canceled -= instance.OnButton5;
            @Button6.started -= instance.OnButton6;
            @Button6.performed -= instance.OnButton6;
            @Button6.canceled -= instance.OnButton6;
            @Button15.started -= instance.OnButton15;
            @Button15.performed -= instance.OnButton15;
            @Button15.canceled -= instance.OnButton15;
            @Button16.started -= instance.OnButton16;
            @Button16.performed -= instance.OnButton16;
            @Button16.canceled -= instance.OnButton16;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnHatUp(InputAction.CallbackContext context);
        void OnHatDown(InputAction.CallbackContext context);
        void OnHatLeft(InputAction.CallbackContext context);
        void OnHatRight(InputAction.CallbackContext context);
        void OnButton3(InputAction.CallbackContext context);
        void OnButton4(InputAction.CallbackContext context);
        void OnButton2(InputAction.CallbackContext context);
        void OnButton11(InputAction.CallbackContext context);
        void OnButton9(InputAction.CallbackContext context);
        void OnButton5(InputAction.CallbackContext context);
        void OnButton6(InputAction.CallbackContext context);
        void OnButton15(InputAction.CallbackContext context);
        void OnButton16(InputAction.CallbackContext context);
    }
}
